CREATE TABLE [dbo].[rnd_Email](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Value] [nvarchar](300) NOT NULL,
 CONSTRAINT [PK_rnd_Email] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
